[package]
name = "mavagks_terminal_games"
version = "0.12.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
strum = "0.27.2"
strum_macros = "0.27.2"
array2d = "0.3.2"
rand = "0.9.2"
num = "0.4.3"
num-traits = "0.2.19"
chrono = "0.4.24"